apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit323-deployment
  labels:
    app: sit323app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit323app
  template:
    metadata:
      labels:
        app: sit323app
    spec:
      containers:
      - name: sit323-container
        image: alenantony/sit323app:latest
        ports:
        - containerPort: 3000
