apiVersion: v1
kind: Service
metadata:
  name: sit323-service
spec:
  type: NodePort
  selector:
    app: sit323app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
